### ISSUE TITLE
Node run.js ends abruptly with no error

### ISSUE THREAD

**Issue by jdellaria** [IBM/tjbot-sports-buddy#21]
Love the demo. I am trying to get this to run on my Ubuntu 16.04 VMWare insstance. It looks like it is going to work and Watson Says "Hi there... I am awake." but then it does not wait for me to reply and goes to the command prompt with no errors.. Any idea of what May be happening? 

```
jdellaria@ubuntu:~/IBM/tjbot-sports-buddy$ node run.js
Retrieved MLB Teams
Retrieved MLB standings
Retrieved schedule for date: 2017-07-28T00:00:00
Retrieved schedule for date: 2017-07-31T00:00:00
Retrieved schedule for date: 2017-07-29T00:00:00
Retrieved schedule for date: 2017-08-02T00:00:00
Retrieved schedule for date: 2017-08-01T00:00:00
Retrieved schedule for date: 2017-07-30T00:00:00
Retrieved schedule for date: 2017-08-03T00:00:00
Retrieved MLB schedules TJBot is listening, you may speak now.
Microphone paused for 2.1126080000000003 seconds.
Microphone resumed.
jdellaria@ubuntu:~/IBM/tjbot-sports-buddy$﻿
```

**Comment by stevemar** [comment]
Hey @jdellaria my gut says it's an audio config issue, so, silly question -- does the microphone on your Ubuntu VM work at all? Can you record something? Both @rhagarty and I have used OSX for our demos -- we outlined some of the issues we found with audio configuration here: https://github.com/IBM/tjbot-sports-buddy#troubleshooting

**Comment by jdellaria** [comment]
Yes. I can record Mp3, ogg and wav files by using audio-recorder. The audio quality seems to be rather good. Is there a particular format or device you are looking for? The devices that work for recording are "ES1371/Creative Labs CT2518/ES1373 (Microphone)", "System's default device" and "user defined audio source"

**Comment by rhagarty** [comment]
Hello @jdellaria - I've updated https://github.com/IBM/tjbot-sports-buddy#troubleshooting with some mic tests and fixes. Please let me know if this fixes your issue.

**Comment by jdellaria** [comment]
Perfect!

Thanks!

Jon

**Comment by stevemar** [comment]
I'll take that as I can close this issue now :)

**Comment by jdellaria** [comment]
Sure... :)
