### ISSUE TITLE
Need changes for authentication with "access token" instead of "Username" and "Password"

### ISSUE THREAD

**Issue by ghost** [IBM/tjbot-sports-buddy#43]
IBM cloud has recently made changes to token-based authentication from the usage of username/password. It would be more useful if the subsequent changes are made in this code pattern according to that.

To my knowledge:

config.new.js and run.js are the files which uses the username and password.

**Comment by stevemar** [comment]
@Soundharyaam yes, we just became aware of those changes and will be addressing them soon.

**Comment by ghost** [comment]
@stevemart Thanks!

**Comment by rhagarty** [comment]
This was addressed in latest PR
